class ConfigConstants:
    MAX_REPAIR_HOURS = 1000
    MIN_REPAIR_HOURS = 0.5
    MAX_DISCOUNT_PERCENTAGE = 50
    MIN_SERVICE_COST = 10  
    MAX_SERVICE_COST = 10000
    WARRANTY_PERIOD_DAYS = 90
    MAX_PARTS_QUANTITY = 1000
    MIN_EMPLOYEE_RATING = 1
    MAX_EMPLOYEE_RATING = 5
    STANDARD_REPAIR_TIME_HOURS = 2
    URGENT_REPAIR_MULTIPLIER = 1.5