class ValidationConstants:
    MIN_CLIENT_NAME_LENGTH = 2
    MAX_CLIENT_NAME_LENGTH = 100
    MIN_PHONE_LENGTH = 10
    MAX_PHONE_LENGTH = 15
    MIN_EMAIL_LENGTH = 5
    MAX_EMAIL_LENGTH = 255
    MIN_ADDRESS_LENGTH = 5
    MAX_ADDRESS_LENGTH = 200